<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php $banner = $block->getBannerData(); ?>

<button 
    class="ivy-checkout-button ivy-express-cart-button" 
    data-cart-value="<?= $block->getQuote()->getBaseGrandTotal() ?>"
    data-shop-category="<?= $banner->getMcc() ?>"
    data-currency-code="<?= $block->getQuote()->getStore()->getCurrentCurrencyCode(); ?>"
    data-locale="<?= $banner->getLocale() ?>"
    style="visibility: hidden">
</button>

<script>
require(['jquery','mage/url','Magento_Ui/js/model/messageList','domReady!'], function ($,url,messageList) {
    $( ".ivy-express-cart-button" ).click(function() {
        var linkUrl = url.build('ivypayment/checkout/index/express/1');
        
        $.ajax({
            url: linkUrl,
            type: 'POST',
            success: function(response) {
                window.startIvyCheckout(response.redirectUrl,'popup');
            },
            error: function(xhr, status, errorThrown) {
                messageList.addErrorMessage({ message: errorThrown });
            }
        });
    });
}); 
  
</script>